create database GOFF;
use GOFF;
create table clientes(
id int primary key identity(1,1),
nombre varchar(30),
edad int
)

INSERT INTO clientes(nombre, edad)
VALUES
    ('Juan Pérez', 25),
    ('María García', 30),
    ('Carlos Rodríguez', 22),
    ('Laura Martínez', 28),
    ('José González', 35),
    ('Ana López', 27),
    ('Pedro Sánchez', 40),
    ('Isabel Ramírez', 32),
    ('Francisco Díaz', 26),
    ('Elena Castro', 21),
    ('Miguel Fernández', 45),
    ('Luis Torres', 33),
    ('Carmen Ruiz', 29),
    ('Raúl Herrera', 38),
    ('Sofía Medina', 24),
    ('Diego Vargas', 31),
    ('Victoria Morales', 37),
    ('Javier Jiménez', 23),
    ('Lucía Flores', 36),
    ('Ángel Silva', 39),
    ('Patricia Herrera', 34),
    ('Rubén Mendoza', 42),
    ('Valeria Gómez', 28),
    ('Daniel Ortega', 41),
    ('Adriana Núñez', 33),
    ('Alejandro Castillo', 29),
    ('Silvia Aguilar', 44),
    ('Hugo Miranda', 26),
    ('Gabriela Cruz', 35),
    ('Ricardo Ríos', 30),
    ('Natalia Varela', 37),
    ('Gustavo Cordero', 28),
    ('Olga Montes', 43),
    ('Fernando Herrera', 32),
    ('Emma Salazar', 27),
    ('Jorge Medina', 39),
    ('Marina Soto', 31),
    ('Martín Rojas', 34),
    ('Lorena Paredes', 40),
    ('Renata Torres', 29),
    ('Martín López', 37),
    ('Gabriela Ramírez', 31),
    ('Andrés Castro', 25),
    ('Isabella Rodríguez', 33),
    ('Diego Sánchez', 28),
    ('Valentina Díaz', 35),
    ('Emilio Gómez', 30),
    ('Camila Mendoza', 26),
    ('Joaquín Vargas', 42),
    ('Ana Sofía García', 36),
    ('David Pérez', 27),
    ('Renzo Herrera', 39),
    ('Juliana Medina', 24),
    ('Mateo Ruiz', 32),
    ('Regina Jiménez', 38),
    ('Alejandro Núñez', 41),
    ('Luna Silva', 23),
    ('Héctor Morales', 40),
    ('Valeria Salazar', 34),
    ('Gael Cruz', 31),
    ('René Aguilar', 37),
    ('Mariana Rojas', 29),
    ('Axel Paredes', 44),
    ('Eva Montes', 28),
    ('Sebastián Ortega', 35),
    ('Luciana Torres', 30),
    ('Santiago Mendoza', 33),
    ('Alicia Soto', 39),
    ('Federico Varela', 26),
    ('Natalie Cordero', 43),
    ('Simón Castillo', 32),
    ('Isabel Miranda', 27),
    ('Felipe Núñez', 38),
    ('Catalina Rojas', 25),
    ('León Jiménez', 34),
    ('Abril Herrera', 40),
    ('Maximiliano Ramírez', 36),
    ('Daniela Pérez', 29),
    ('Hugo Medina', 37);